### ISSUE TITLE
Should have an option to not display transaction details in notifications

### ISSUE THREAD

**Issue by w2vy** [RunOnFlux/ssp-wallet#65]
Many have notifications visible while phone is locked and screen lock may be on a long delay.
I think it would be a good idea to add UI options that:

1) simplify the notification to "You have a transaction request" (so no details are visible to unidentified users)
2) verify bio-metrics when opening/waking up the app (Don't rely on screen lock)

I also think that the default for both should be Enabled so the default behavior is to provide confidentiality and highest security

**Comment by TheTrunk** [comment]
1. Yes that is doable. It is actually ssp-relay which sends the notifications to the ssp-key with the already decoded information, since the raw transaction hex routes from ssp wallet to ssp relay to ssp key. In couple versions back that was the behaviour, then it was switched to show more information. We can discuss what is better and have some settings toggle (but that might be trickier as its ssp relay related which has no information about settings of key)
2. I was trying to reproduce behaviour of similar 2 factor authentication apps, such as mobile banking. Usually Wallets have sign in requirements to unlock the app and 2fa apps don't. It is possible to add it, I found it unnecessary - copying behaviour of 2fa apps only the actual security actions have this verifications. We can add settings toggle for this.
